# Generated by Django 3.0.4 on 2020-03-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='id',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='classplan',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student_helper.Users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classplan',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='classplan',
            unique_together={('uid', 'cid', 'week', 'position')},
        ),
    ]
